export interface GameTheme {
  id: string;
  name: string;
  description: string;
  requiredPuzzles: number;
  isPremium: boolean;
  tileWhite: string;
  tileBlack: string;
  tileGray: string;
  tileLocked: string;
  accent: string;
  pathColor: string;
  preview: [string, string];
  previewAccent?: string;
}

export const THEMES: GameTheme[] = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Warm ivory and charcoal',
    requiredPuzzles: 0,
    isPremium: false,
    tileWhite: '#F0EBE3',
    tileBlack: '#2C2F3A',
    tileGray: '#4A4E5C',
    tileLocked: '#7B6E5D',
    accent: '#D4A04A',
    pathColor: '#D4A04A',
    preview: ['#F0EBE3', '#2C2F3A'],
  },
  {
    id: 'arctic',
    name: 'Arctic',
    description: 'Icy blue and frost white',
    requiredPuzzles: 8,
    isPremium: false,
    tileWhite: '#E8F4F8',
    tileBlack: '#1B3A4B',
    tileGray: '#3D6478',
    tileLocked: '#5B8BA0',
    accent: '#5CC8E8',
    pathColor: '#5CC8E8',
    preview: ['#E8F4F8', '#1B3A4B'],
  },
  {
    id: 'ember',
    name: 'Ember',
    description: 'Smoldering red and coal',
    requiredPuzzles: 18,
    isPremium: false,
    tileWhite: '#F8E8D8',
    tileBlack: '#3A1B1B',
    tileGray: '#6B3A3A',
    tileLocked: '#8B5A4A',
    accent: '#E86838',
    pathColor: '#FF8C5A',
    preview: ['#F8E8D8', '#3A1B1B'],
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Deep emerald and moss',
    requiredPuzzles: 30,
    isPremium: false,
    tileWhite: '#E4F0E4',
    tileBlack: '#1B3A22',
    tileGray: '#3A6844',
    tileLocked: '#5A8860',
    accent: '#4CAF7D',
    pathColor: '#6AD49A',
    preview: ['#E4F0E4', '#1B3A22'],
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    description: 'Royal purple and lavender',
    requiredPuzzles: 45,
    isPremium: false,
    tileWhite: '#EDE4F8',
    tileBlack: '#2A1B42',
    tileGray: '#4A3A6B',
    tileLocked: '#6A5A8B',
    accent: '#9B6AD4',
    pathColor: '#B88AE8',
    preview: ['#EDE4F8', '#2A1B42'],
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Golden hour warmth',
    requiredPuzzles: 60,
    isPremium: false,
    tileWhite: '#FFF0D4',
    tileBlack: '#3A2A18',
    tileGray: '#6B5A3A',
    tileLocked: '#8B7A5A',
    accent: '#F0923A',
    pathColor: '#FFB060',
    preview: ['#FFF0D4', '#3A2A18'],
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Deep sea and coral reef',
    requiredPuzzles: 75,
    isPremium: false,
    tileWhite: '#D4F0F8',
    tileBlack: '#0A2A3A',
    tileGray: '#2A5A6B',
    tileLocked: '#4A7A8B',
    accent: '#00C8B0',
    pathColor: '#40E8D0',
    preview: ['#D4F0F8', '#0A2A3A'],
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Volcanic glass and neon',
    requiredPuzzles: 90,
    isPremium: false,
    tileWhite: '#D8D8E0',
    tileBlack: '#0A0A12',
    tileGray: '#2A2A3A',
    tileLocked: '#4A4A5A',
    accent: '#00FF88',
    pathColor: '#00FF88',
    preview: ['#D8D8E0', '#0A0A12'],
  },
  {
    id: 'frosted_glass',
    name: 'Frosted Glass',
    description: 'Translucent ice with crystalline edges',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#E0F0FA',
    tileBlack: '#2A4A60',
    tileGray: '#5A8098',
    tileLocked: '#4A7090',
    accent: '#88D8F8',
    pathColor: '#A0E8FF',
    preview: ['#E0F0FA', '#2A4A60'],
    previewAccent: '#88D8F8',
  },
  {
    id: 'rose_gold',
    name: 'Rose Gold',
    description: 'Luxurious blush and metallic pink',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#FFF0EC',
    tileBlack: '#8B4A5A',
    tileGray: '#C07888',
    tileLocked: '#9A6070',
    accent: '#E8A0B0',
    pathColor: '#FFB8C8',
    preview: ['#FFF0EC', '#8B4A5A'],
    previewAccent: '#E8A0B0',
  },
  {
    id: 'neon_spark',
    name: 'Neon Spark',
    description: 'Electric cyan on pitch black',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#142840',
    tileBlack: '#020408',
    tileGray: '#0A1420',
    tileLocked: '#081018',
    accent: '#00F0FF',
    pathColor: '#00F0FF',
    preview: ['#142840', '#020408'],
    previewAccent: '#00F0FF',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Northern lights dancing on snow',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#E8F8F0',
    tileBlack: '#1A2848',
    tileGray: '#2A4068',
    tileLocked: '#3A5078',
    accent: '#48D8A0',
    pathColor: '#80F0C0',
    preview: ['#E8F8F0', '#1A2848'],
    previewAccent: '#48D8A0',
  },
  {
    id: 'molten',
    name: 'Molten',
    description: 'Lava flows through obsidian cracks',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#FF8830',
    tileBlack: '#1A0808',
    tileGray: '#3A1010',
    tileLocked: '#2A0C0C',
    accent: '#FF4020',
    pathColor: '#FFAA40',
    preview: ['#FF8830', '#1A0808'],
    previewAccent: '#FF4020',
  },
  {
    id: 'mirror',
    name: 'Mirror',
    description: 'Chrome reflections, silver and steel',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#E8E8F0',
    tileBlack: '#585868',
    tileGray: '#787888',
    tileLocked: '#686878',
    accent: '#C0C0D8',
    pathColor: '#E0E0FF',
    preview: ['#E8E8F0', '#585868'],
    previewAccent: '#C0C0D8',
  },
  {
    id: 'sakura',
    name: 'Sakura',
    description: 'Cherry blossoms on soft cream',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#FFF5F0',
    tileBlack: '#5A3040',
    tileGray: '#8A5868',
    tileLocked: '#6A4050',
    accent: '#F088A8',
    pathColor: '#FFA8C0',
    preview: ['#FFF5F0', '#5A3040'],
    previewAccent: '#F088A8',
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    description: 'Deep space with stardust trails',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#D8C8F8',
    tileBlack: '#0A0818',
    tileGray: '#1A1030',
    tileLocked: '#1A1028',
    accent: '#A868F0',
    pathColor: '#C890FF',
    preview: ['#D8C8F8', '#0A0818'],
    previewAccent: '#A868F0',
  },
  {
    id: 'emerald_cut',
    name: 'Emerald Cut',
    description: 'Polished gemstone facets',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#D0F8E0',
    tileBlack: '#0A3020',
    tileGray: '#1A5038',
    tileLocked: '#184830',
    accent: '#30E888',
    pathColor: '#60FFA8',
    preview: ['#D0F8E0', '#0A3020'],
    previewAccent: '#30E888',
  },
  {
    id: 'copper_patina',
    name: 'Copper Patina',
    description: 'Aged copper with teal oxidation',
    requiredPuzzles: 0,
    isPremium: true,
    tileWhite: '#D8F0E8',
    tileBlack: '#4A2818',
    tileGray: '#3A6858',
    tileLocked: '#386050',
    accent: '#C87838',
    pathColor: '#E8A060',
    preview: ['#D8F0E8', '#4A2818'],
    previewAccent: '#C87838',
  },
];

export const FREE_THEMES = THEMES.filter(t => !t.isPremium);
export const PREMIUM_THEMES = THEMES.filter(t => t.isPremium);

export function getThemeById(id: string): GameTheme {
  return THEMES.find(t => t.id === id) ?? THEMES[0];
}
